import type { MetadataRoute } from "next";

import { site } from "@/content/site";

/**
 * Web app manifest, served at /manifest.webmanifest.
 *
 * This is what an installed shortcut, an Android home screen icon and a Windows
 * tile read. Without it those fall back to a screenshot of the page or a
 * cropped favicon.
 *
 * Two icon entries, not one. `purpose: "any"` is the icon as drawn. `maskable`
 * is the same artwork with a wide margin, because Android applies its own mask
 * (a circle on one launcher, a squircle on the next) and crops up to twenty per
 * cent off each side to do it. Ship only "any" and the badge loses its edge on
 * every device that masks; ship only "maskable" and it sits small and lost
 * inside its padding everywhere that does not. Both are generated by
 * scripts/make-icons.mjs.
 *
 * The mark itself is declared through Next's file conventions in this
 * directory (favicon.ico, icon.svg, icon.png, apple-icon.png) rather than
 * repeated here.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.legalName,
    short_name: site.shortName,
    description: site.description,
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    // White, because that is the field the mark sits on: a green splash behind
    // a white icon tile would flash the wrong way round on launch.
    background_color: "#ffffff",
    theme_color: "#175c25",
    lang: "en-IN",
    categories: ["business", "utilities"],
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icon-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
